# -*- coding: utf-8 -*-
"""Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bs7-2bN5zBSAB5hqxcqnfwpVYQ-mhsLX
"""

print("Simple Calculator")
print("Created by Shreya Reddy")

while True:
    # take numbers
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))

    print("\nChoose operation:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")

    choice = input("Enter choice (1-4): ")

    if choice == "1":
        print("Result =", num1 + num2)

    elif choice == "2":
        print("Result =", num1 - num2)

    elif choice == "3":
        print("Result =", num1 * num2)

    elif choice == "4":
        if num2 != 0:
            print("Result =", num1 / num2)
        else:
            print("Cannot divide by zero")

    else:
        print("Invalid choice")

    again = input("Do you want to calculate again? (yes/no): ")
    if again.lower() != "yes":
        print("Calculator closed")
        break