# -*- coding: utf-8 -*-
"""password_generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nthlHwTbI6ski2VjVJssUlDjBkBzNjvK
"""

import random
import string

print("Password Generator")
print("Created by Shreya Reddy")

while True:
    length = int(input("Enter password length: "))

    characters = string.ascii_letters + string.digits + string.punctuation

    password = ''.join(random.choice(characters) for i in range(length))

    print("Generated Password:", password)

    again = input("Generate another password? (yes/no): ")
    if again.lower() != "yes":
        print("Program closed")
        break